// port-lint: source codex-backend-openapi-models/src/models/code_task_details_response.rs
package ai.solace.coder.backend.openapi.models.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonElement

/*
 * codex-backend
 *
 * codex-backend
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */
@Serializable
data class CodeTaskDetailsResponse(
    @SerialName("task") val task: TaskResponse,
    @SerialName("current_user_turn") val currentUserTurn: Map<String, JsonElement>? = null,
    @SerialName("current_assistant_turn") val currentAssistantTurn: Map<String, JsonElement>? = null,
    @SerialName("current_diff_task_turn") val currentDiffTaskTurn: Map<String, JsonElement>? = null,
) {
    companion object {
        fun new(task: TaskResponse): CodeTaskDetailsResponse =
            CodeTaskDetailsResponse(task = task)
    }
}
