// port-lint: source codex-backend-openapi-models/src/models/credit_status_details.rs
package ai.solace.coder.backend.openapi.models.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonElement

/*
 * codex-backend
 *
 * codex-backend
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */
@Serializable
data class CreditStatusDetails(
    @SerialName("has_credits") val hasCredits: Boolean,
    @SerialName("unlimited") val unlimited: Boolean,
    @SerialName("balance") val balance: String? = null,
    @SerialName("approx_local_messages") val approxLocalMessages: List<JsonElement>? = null,
    @SerialName("approx_cloud_messages") val approxCloudMessages: List<JsonElement>? = null,
) {
    companion object {
        fun new(hasCredits: Boolean, unlimited: Boolean): CreditStatusDetails =
            CreditStatusDetails(
                hasCredits = hasCredits,
                unlimited = unlimited,
            )
    }
}
