// port-lint: source codex-backend-openapi-models/src/models/external_pull_request_response.rs
package ai.solace.coder.backend.openapi.models.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/*
 * codex-backend
 *
 * codex-backend
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */
@Serializable
data class ExternalPullRequestResponse(
    @SerialName("id") val id: String,
    @SerialName("assistant_turn_id") val assistantTurnId: String,
    @SerialName("pull_request") val pullRequest: GitPullRequest,
    @SerialName("codex_updated_sha") val codexUpdatedSha: String? = null,
) {
    companion object {
        fun new(
            id: String,
            assistantTurnId: String,
            pullRequest: GitPullRequest,
        ): ExternalPullRequestResponse =
            ExternalPullRequestResponse(
                id = id,
                assistantTurnId = assistantTurnId,
                pullRequest = pullRequest,
                codexUpdatedSha = null,
            )
    }
}

