// port-lint: source codex-backend-openapi-models/src/models/git_pull_request.rs
package ai.solace.coder.backend.openapi.models.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonElement

/*
 * codex-backend
 *
 * codex-backend
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */
@Serializable
data class GitPullRequest(
    @SerialName("number") val number: Int,
    @SerialName("url") val url: String,
    @SerialName("state") val state: String,
    @SerialName("merged") val merged: Boolean,
    @SerialName("mergeable") val mergeable: Boolean,
    @SerialName("draft") val draft: Boolean? = null,
    @SerialName("title") val title: String? = null,
    @SerialName("body") val body: String? = null,
    @SerialName("base") val base: String? = null,
    @SerialName("head") val head: String? = null,
    @SerialName("base_sha") val baseSha: String? = null,
    @SerialName("head_sha") val headSha: String? = null,
    @SerialName("merge_commit_sha") val mergeCommitSha: String? = null,
    @SerialName("comments") val comments: JsonElement? = null,
    @SerialName("diff") val diff: JsonElement? = null,
    @SerialName("user") val user: JsonElement? = null,
) {
    companion object {
        fun new(
            number: Int,
            url: String,
            state: String,
            merged: Boolean,
            mergeable: Boolean,
        ): GitPullRequest =
            GitPullRequest(
                number = number,
                url = url,
                state = state,
                merged = merged,
                mergeable = mergeable,
                draft = null,
                title = null,
                body = null,
                base = null,
                head = null,
                baseSha = null,
                headSha = null,
                mergeCommitSha = null,
                comments = null,
                diff = null,
                user = null,
            )
    }
}

