// port-lint: source codex-backend-openapi-models/src/models/paginated_list_task_list_item_.rs
package ai.solace.coder.backend.openapi.models.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/*
 * codex-backend
 *
 * codex-backend
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */
@Serializable
data class PaginatedListTaskListItem(
    @SerialName("items") val items: List<TaskListItem>,
    @SerialName("cursor") val cursor: String? = null,
) {
    companion object {
        fun new(items: List<TaskListItem>): PaginatedListTaskListItem =
            PaginatedListTaskListItem(
                items = items,
                cursor = null,
            )
    }
}

