// port-lint: source codex-backend-openapi-models/src/models/rate_limit_window_snapshot.rs
package ai.solace.coder.backend.openapi.models.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/*
 * codex-backend
 *
 * codex-backend
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */
@Serializable
data class RateLimitWindowSnapshot(
    @SerialName("used_percent") val usedPercent: Int,
    @SerialName("limit_window_seconds") val limitWindowSeconds: Int,
    @SerialName("reset_after_seconds") val resetAfterSeconds: Int,
    @SerialName("reset_at") val resetAt: Int,
) {
    companion object {
        fun new(
            usedPercent: Int,
            limitWindowSeconds: Int,
            resetAfterSeconds: Int,
            resetAt: Int,
        ): RateLimitWindowSnapshot = RateLimitWindowSnapshot(
            usedPercent = usedPercent,
            limitWindowSeconds = limitWindowSeconds,
            resetAfterSeconds = resetAfterSeconds,
            resetAt = resetAt,
        )
    }
}
