// port-lint: source codex-backend-openapi-models/src/models/rate_limit_status_details.rs
package ai.solace.coder.backend.openapi.models.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/*
 * codex-backend
 *
 * codex-backend
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */
@Serializable
data class RateLimitStatusDetails(
    @SerialName("allowed") val allowed: Boolean,
    @SerialName("limit_reached") val limitReached: Boolean,
    @SerialName("primary_window") val primaryWindow: RateLimitWindowSnapshot? = null,
    @SerialName("secondary_window") val secondaryWindow: RateLimitWindowSnapshot? = null,
) {
    companion object {
        fun new(allowed: Boolean, limitReached: Boolean): RateLimitStatusDetails =
            RateLimitStatusDetails(
                allowed = allowed,
                limitReached = limitReached,
            )
    }
}
