// port-lint: source codex-backend-openapi-models/src/models/rate_limit_status_payload.rs
package ai.solace.coder.backend.openapi.models.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/*
 * codex-backend
 *
 * codex-backend
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */
@Serializable
data class RateLimitStatusPayload(
    @SerialName("plan_type") val planType: PlanType,
    @SerialName("rate_limit") val rateLimit: RateLimitStatusDetails? = null,
    @SerialName("credits") val credits: CreditStatusDetails? = null,
) {
    companion object {
        fun new(planType: PlanType): RateLimitStatusPayload =
            RateLimitStatusPayload(planType = planType)
    }
}

@Serializable
enum class PlanType {
    @SerialName("guest") Guest,
    @SerialName("free") Free,
    @SerialName("go") Go,
    @SerialName("plus") Plus,
    @SerialName("pro") Pro,
    @SerialName("free_workspace") FreeWorkspace,
    @SerialName("team") Team,
    @SerialName("business") Business,
    @SerialName("education") Education,
    @SerialName("quorum") Quorum,
    @SerialName("k12") K12,
    @SerialName("enterprise") Enterprise,
    @SerialName("edu") Edu,
}
