// port-lint: source codex-backend-openapi-models/src/models/task_list_item.rs
package ai.solace.coder.backend.openapi.models.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonElement

/*
 * codex-backend
 *
 * codex-backend
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */
@Serializable
data class TaskListItem(
    @SerialName("id") val id: String,
    @SerialName("title") val title: String,
    @SerialName("has_generated_title") val hasGeneratedTitle: Boolean? = null,
    @SerialName("updated_at") val updatedAt: Double? = null,
    @SerialName("created_at") val createdAt: Double? = null,
    @SerialName("task_status_display") val taskStatusDisplay: Map<String, JsonElement>? = null,
    @SerialName("archived") val archived: Boolean,
    @SerialName("has_unread_turn") val hasUnreadTurn: Boolean,
    @SerialName("pull_requests") val pullRequests: List<ExternalPullRequestResponse>? = null,
) {
    companion object {
        fun new(
            id: String,
            title: String,
            hasGeneratedTitle: Boolean?,
            archived: Boolean,
            hasUnreadTurn: Boolean,
        ): TaskListItem =
            TaskListItem(
                id = id,
                title = title,
                hasGeneratedTitle = hasGeneratedTitle,
                updatedAt = null,
                createdAt = null,
                taskStatusDisplay = null,
                archived = archived,
                hasUnreadTurn = hasUnreadTurn,
                pullRequests = null,
            )
    }
}

