// port-lint: source codex-backend-openapi-models/src/models/task_response.rs
package ai.solace.coder.backend.openapi.models.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonElement

/*
 * codex-backend
 *
 * codex-backend
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */
@Serializable
data class TaskResponse(
    @SerialName("id") val id: String,
    @SerialName("created_at") val createdAt: Double? = null,
    @SerialName("title") val title: String,
    @SerialName("has_generated_title") val hasGeneratedTitle: Boolean? = null,
    @SerialName("current_turn_id") val currentTurnId: String? = null,
    @SerialName("has_unread_turn") val hasUnreadTurn: Boolean? = null,
    @SerialName("denormalized_metadata") val denormalizedMetadata: Map<String, JsonElement>? = null,
    @SerialName("archived") val archived: Boolean,
    @SerialName("external_pull_requests") val externalPullRequests: List<ExternalPullRequestResponse>,
) {
    companion object {
        fun new(
            id: String,
            title: String,
            archived: Boolean,
            externalPullRequests: List<ExternalPullRequestResponse>,
        ): TaskResponse = TaskResponse(
            id = id,
            title = title,
            archived = archived,
            externalPullRequests = externalPullRequests,
        )
    }
}
